# Generated by Django 4.1 on 2023-10-06 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_apagno_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='nuevoevento',
            name='categoria',
            field=models.CharField(default='Sin categoria', max_length=100),
        ),
        migrations.AlterField(
            model_name='nuevoevento',
            name='fecha',
            field=models.DateField(default='2023-10-06'),
        ),
        migrations.AlterField(
            model_name='nuevoevento',
            name='hora',
            field=models.TimeField(default='00:02'),
        ),
    ]
