# Generated by Django 4.1 on 2023-10-06 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_apagno_app', '0002_categorias_alter_nuevoevento_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nuevoevento',
            name='categoria',
            field=models.ForeignKey(default='Sin categoria', on_delete=django.db.models.deletion.CASCADE, to='perfil_apagno_app.categorias'),
        ),
        migrations.AlterField(
            model_name='nuevoevento',
            name='hora',
            field=models.TimeField(default='00:28'),
        ),
    ]
