# Generated by Django 4.1 on 2023-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_apagno_app', '0003_alter_nuevoevento_categoria_alter_nuevoevento_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevoevento',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='eventos/'),
        ),
        migrations.AlterField(
            model_name='nuevoevento',
            name='fecha',
            field=models.DateField(default='2023-10-12'),
        ),
        migrations.AlterField(
            model_name='nuevoevento',
            name='hora',
            field=models.TimeField(default='02:28'),
        ),
    ]
