# Generated by Django 4.1 on 2023-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "perfil_apagno_app",
            "0004_nuevoevento_asistentes_alter_nuevoevento_fecha_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuevoevento",
            name="hora",
            field=models.TimeField(default="15:49"),
        ),
    ]
