# Generated by Django 4.1 on 2023-10-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil_apagno_app", "0005_alter_nuevoevento_hora"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuevoevento",
            name="fecha",
            field=models.DateField(default="2023-10-14"),
        ),
        migrations.AlterField(
            model_name="nuevoevento",
            name="hora",
            field=models.TimeField(default="18:42"),
        ),
        migrations.AlterField(
            model_name="nuevoevento",
            name="imagen",
            field=models.FileField(blank=True, upload_to="eventos_images/"),
        ),
    ]
