# Generated by Django 4.1 on 2023-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "perfil_apagno_app",
            "0006_alter_nuevoevento_fecha_alter_nuevoevento_hora_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuevoevento",
            name="hora",
            field=models.TimeField(default="18:43"),
        ),
    ]
