# Generated by Django 4.1 on 2023-11-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("perfil_apagno_app", "0011_alter_nuevoevento_hora_alter_user_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nuevoevento",
            name="hora",
            field=models.TimeField(default="17:47"),
        ),
    ]
